- name: change route53
  route53:
    state: present
    zone: bookstobook.com
    record: www.bookstobook.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "8f261342-d815-4802-97ae-e3a996be01ab"
